In [45]:
import numpy as np

In [46]:
np.array ([10, 2, 35])

array([10,  2, 35])

In [47]:
list (range (5))

[0, 1, 2, 3, 4]

In [48]:
np.arange(start = 2, stop = 14, step = 2)

array([ 2,  4,  6,  8, 10, 12])

In [49]:
build_in_time = %timeit -o np.array(range(1_000_000))

52.2 ms ± 346 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
numpy_time = %timeit -o np.arange(1_000_000)

923 µs ± 4.02 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [51]:
print (f"Numpy is {build_in_time.average/numpy_time.average} times faster")

Numpy is 56.51381764698122 times faster


In [52]:
np.linspace(start=-5, stop=5, num=9)

array([-5.  , -3.75, -2.5 , -1.25,  0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [53]:
np.zeros(3)

array([0., 0., 0.])

In [54]:
np.zeros((2, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.ones(shape=(2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
np.empty(shape=(2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
from numpy import shape


empty_time = %timeit -o np.empty(shape= 100_000)
ones_time = %timeit -o np.ones(shape= 100_000)

print(f"\nempty is {ones_time.average/empty_time.average} times faster")

257 ns ± 2.17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
10.4 µs ± 28.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

empty is 40.387452759947045 times faster


In [58]:
np.full(shape= (2, 4, 3), fill_value= 42)

array([[[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]]])

In [59]:
np.full(shape= (1, 3, 3), fill_value= True)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [60]:
values = [0, 1, 2, 3, 4]
int_arr = np.array(values, dtype='int')
int_arr, int_arr.dtype

(array([0, 1, 2, 3, 4]), dtype('int32'))

In [61]:
bool_arr = np.array(values, dtype = 'bool')
bool_arr, bool_arr.dtype

(array([False,  True,  True,  True,  True]), dtype('bool'))

In [62]:
values = [0, 1, 2.5, 3, 4]
float_arr = np.array(values)
float_arr, float_arr.dtype

(array([0. , 1. , 2.5, 3. , 4. ]), dtype('float64'))

In [63]:
values = [0, 1, 2, 3, 4]
int_arr = np.array(values, dtype='int')

int_arr[0] = 1.5 
int_arr

array([1, 1, 2, 3, 4])

In [64]:
values = [1, 2, 3, 4]
one_dim_arr = np.array(values)
one_dim_arr

array([1, 2, 3, 4])

In [65]:
one_dim_arr.shape

(4,)

In [66]:
one_dim_arr.ndim

1

In [67]:
values = [[1, 2, 3, 4],
          [1, 2, 3, 4],
          [1, 2, 3, 4]]
two_dim_arr = np.array(values)
two_dim_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [68]:
two_dim_arr.shape

(3, 4)

In [70]:
two_dim_arr.ndim

2

In [71]:
values = [[[1, 2, 3, 4]]*3]*6
three_dim_arr = np.array(values)
three_dim_arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [72]:
three_dim_arr.shape

(6, 3, 4)

In [73]:
three_dim_arr.ndim

3